app_name: alexdevid_portal
db:
    name: aggr
    username: root
    password: ''
    host: localhost
routes:
    category:
        route: '/category/*'
        controller: category
    picture:
        route: '/picture/*'
        controller: picture
